apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - exam.odeybright.me
      secretName: exam-tls
  rules:
    - host: exam.odeybright.me
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  name: http
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
