apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/starburn-hub/final-exam.git
    targetRevision: main
    ref: starburnRepo
  - repoURL: https://helm.nginx.com/stable
    chart: ingress-nginx
    targetRevision: 4.5.2
    helm:
      releaseName: nginx-ingress
      valueFiles:
        - $starburnRepo/argocd_apps/values/ingress-nginx.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
