apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sock-shop
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/hostspaceng/helm-charts.git
    targetRevision: main
    path: ./      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
